server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 60.204.128.243
      port: 8500
      discovery:
#        hostname: 60.204.128.243
        service-name: ${spring.application.name}
        # 开启心跳检测
        heartbeat:
          enabled: true
